version: 0.0
os: linux
files:
  - source: imagedefinitions.json
    destination: /home/ubuntu
hooks:
  ApplicationStart:
    - location: scripts/start-container.sh
      timeout: 300
      runas: ubuntu
